### ISSUE TITLE
Time lib

### ISSUE THREAD

**Issue by enrutador** [jtaczanowski/esp8266_graphite_temperature#1]
Hi and good job
For me to work I had to change the lib:

 #include <Time.h> 

for  the :

#include <TimeLib.h>

regards

**Comment by jtaczanowski** [comment]
Hi!
Thank you for your message. I checked it and It also works for me with TimeLib.h
The problem with Time.h is described here [https://forum.arduino.cc/index.php?topic=451360.0](url)
You are probably using Windows ;)

changed in commit:
[https://github.com/jtaczanowski/esp8266_graphite_temperature/commit/a5a640d8ec4b2f0f016707ad26e86e58c7e44b42](url)
